cd /var/www/sphinx/sphinx/nitrokey-documentation

# pull new content
git pull

# build english version
sphinx-build -D language='en' -b html . /var/www/sphinx/www/static/ 

# generate language files and push
sphinx-build -b gettext . ./locales/
sphinx-intl update -p ./locales/ -l de -l fr -l es
git add --all
git commit -m "Language Files generated by Sphinx"
git push
