#!/bin/bash
export TZ="Europe/Berlin"

# Get the directory where the script is located
SCRIPT_DIR=$(dirname "$(realpath "$0")")
SCRIPT_NAME=$(basename "$0")

# Change to the script's directory
cd "$SCRIPT_DIR" || exit 1

# Load the environment variables
if [ -f "$SCRIPT_DIR/.env" ]; then
    source "$SCRIPT_DIR/.env"
else
    current_time=$(date +"%Y-%m-%d %H:%M:%S")
    log_message="$current_time [$SCRIPT_NAME] Environment file not found!"
    echo -e "$log_message" >> "$LOGFILE_PATH/webhook.log"
    exit 1
fi

# #
# Generate .pot files based on .rst sources
# #
current_time=$(date +"%Y-%m-%d %H:%M:%S")
log_message="$current_time [$SCRIPT_NAME] Generating .pot files with sphinx-build based on .rst sources"
echo -e "$log_message" >>  "$LOGFILE_PATH/webhook.log"
docker run --rm \
        -v $(pwd)/locales:/docs/locales \
        docker.io/nitrokey/sphinx \
        sphinx-build -b gettext . ./locales/
log_message="$current_time [$SCRIPT_NAME] Done"

# #
# Generate locales for all languages (.po files)
# based on .pot files generated by "sphinx-build -b gettext"
# #
sphinx_args=""
for lang in "${LANGUAGES[@]}"
do
	sphinx_args=$sphinx_args" -l $lang"
done

current_time=$(date +"%Y-%m-%d %H:%M:%S")
log_message="$current_time [$SCRIPT_NAME] Generating .po files based on .pot files generated by sphinx-build"
echo -e "$log_message" >>  "$LOGFILE_PATH/webhook.log"
docker run --rm \
        -v $(pwd)/locales:/docs/locales \
        docker.io/nitrokey/sphinx \
        sphinx-intl update -p ./locales/ $sphinx_args 
log_message="$current_time [$SCRIPT_NAME] Done"
