#!/bin/bash

# Load environment variables from config.env
if [ -f ./.env ]; then
  source ./.env
else
  echo "Environment file not found!"
  exit 1
fi

# #
# Generate .pot files based on .rst sources
# #
docker run --rm \
        -v $(pwd)/locales:/docs/locales \
        docker.io/nitrokey/sphinx \
        sphinx-build -b gettext . ./locales/

# #
# Generate locales for all languages (.po files)
# based on .pot files generated by "sphinx-build -b gettext"
# #
sphinx_args=""
for lang in "${LANGUAGES[@]}"
do
	sphinx_args=$sphinx_args" -l $lang"
done

docker run --rm \
        -v $(pwd)/locales:/docs/locales \
        docker.io/nitrokey/sphinx \
        sphinx-intl update -p ./locales/ $sphinx_args 
