[tool.rstcheck]
ignore_directives = [
    "card",
    "tabs",
    "faq",
    "product-table",
]
ignore_messages = [
    # Hyperlinks are not visible by rstcheck as there directives are ignored (mostly faq).
    "faq(.*)Hyperlink target(.*)is not referenced",
    # Docutils raises this warning even when an explicit target link is set.
    # In case it is linked to, it will concert to an error.
    "Duplicate implicit target name: .*",
]

