[tool.rstcheck]
ignore_directives = [
    "card",
    "tabs",
    "faq",
    "product-table",
]
# ignore-messages is needed due to links being used in directives, which
# are not visible by rstcheck as these directives are ignored (mostly faq)
ignore_messages = "faq(.*)Hyperlink target(.*)is not referenced"

