#!/bin/bash
export TZ="Europe/Berlin"

mkdir -p ./logs

# Get the directory where the script is located
SCRIPT_DIR=$(dirname "$(realpath "$0")")
SCRIPT_NAME=$(basename "$0")

# Change to the script's directory
cd "$SCRIPT_DIR" || exit 1

# Load the environment variables
if [ -f "$SCRIPT_DIR/.env" ]; then
    source "$SCRIPT_DIR/.env"
else
    current_time=$(date +"%Y-%m-%d %H:%M:%S")
    log_message="$current_time [$SCRIPT_NAME] Environment file not found!"
    echo -e "$log_message" >> "$LOGFILE_PATH/webhook.log"
    exit 1
fi

build_all=false
# Parse input arguments
for arg in "$@"; do
    case $arg in
    --all-languages)
        build_all=true
        shift
        ;;
    *) ;;
    esac
done

cd $SPHINX_PATH
git pull

if $build_all; then
    bash ./build-locales.sh --all-languages
else
    bash ./build-locales.sh
fi

# add language files to git (add, commit and push)
git add ./source ./locales --all
git commit -m "Language Files generated by Sphinx"
git push

# weblate pull
bash trigger_weblatepull.sh $WEBLATE_API_KEY

# trigger deepl
# bash trigger_deepl.sh $WEBLATE_API_KEY

# weblate commit (deepl-translated files)
bash trigger_weblatecommit.sh $WEBLATE_API_KEY

# weblate push
bash trigger_weblatepush.sh $WEBLATE_API_KEY
