
.. _frontpage: https://nitrokey.com/
.. _WebAuthn.io: https://webauthn.io/
.. _webautn.bin.coffee: https://webauthn.bin.coffee/
.. _chrome://settings/securityKeys: chrome://settings/securityKeys

.. _nfc.fail: https://nfc.fail/

..
  _Links for TRNG questions in Pro/Storage FAQs
.. _scdrand: http://www.incenp.org/dvlpt/scdrand.html
.. _This script: https://lists.gt.net/gnupg/users/80681#80681
.. _created a systemd file: https://support.nitrokey.com/t/scdrand-systemd-service-and-gentoo-ebuild/1164
.. _ebuild for Gentoo: https://github.com/comio/comio-overlay/tree/master/app-crypt/scdtools

.. _BSI TR-03116: https://www.bsi.bund.de/DE/Themen/Unternehmen-und-Organisationen/Standards-und-Zertifizierung/Technische-Richtlinien/TR-nach-Thema-sortiert/tr03116/TR-03116_node.html

.. _disabling Enforce Attestation: https://learn.microsoft.com/en-us/azure/active-directory/authentication/howto-authentication-passwordless-security-key#fido-security-key-optional-settings
