OpenPGP Email Encryption
========================

.. contents:: :local:

.. note::
   OpenPGP support was introduced with the `1.4.0 release of the Nitrokey 3 <https://www.nitrokey.com/news/2023/milestone-nitrokey-3-achieved-openpgp-card-one-time-passwords-and-usb-c-availability>`_ firmware.
   If you have an older version, `update your firmware <firmware-update.html>`_

.. include:: ../../shared/openpgp.rst.inc
