Verify Sealed Hardware
======================


.. contents:: :local:

If you ordered your NitroPC with sealed screws and in a sealed bag, it allows you to check if the NitroPC has been tampered with during shipping.

The bag and all screws of the device have been sealed. For the bag and each of these screws you have received a photo by e-mail.

1. Check each screw individually to see if its individual appearance
   matches the photo. It is best to use a magnifying glass or macro lens
   for this purpose.

   This example shows a sealed screw whose glitter represents an
   individual pattern.

   .. figure:: /components/nitropad/images/Schraube.jpg
      :alt: img


2. If the bag or the screws do not match the photos sent, an
   unauthorized opening of your NitroPC cannot be excluded. In this
   case please contact us to arrange further action.
