Two-Factor Authentication For ERP Software Odoo
===============================================

.. include:: ./product_platform_heading.rst

.. only:: comment 

 .. contents:: :local:

`Odoo <https://www.odoo.com/>`__ is a powerful ERP (Enterprise Resource Planning) software for companies of all sizes. Odoo is available as open source and contains modules for CRM, website, e-commerce, accounting, financial accounting, production, warehouse management, project management, document management, among others.

The secure access to such a central software is especially important and can now be realized with the Nitrokey. For this purpose access is protected by two-factor authentication (2FA) and critical users are given a Nitrokey. From now on during login the Nitrokey will be checked in addition to the user's password. Phishing attacks are thus foiled and your critical company data is protected.

The two-factor authentication can be carried out using one-time passwords (TOTP, RFC 6238) and FIDO U2F, thus enabling Nitrokey Pro, Nitrokey Storage and Nitrokey FIDO U2F to be used. It is also possible to configure authentication centrally and to activate it only for selected users.

The FIDO solution was developed together with our partner `initOS <https://www.initos.com/>`__, who are specialized in the development and customization of Odoo. If you are interested, `contact us <https://www.nitrokey.com/contact>`__.

.. only::: comment

  `Contact <https://www.nitrokey.com/contact>`__

Video: Two-Factor Authentication With The Nitrokey FIDO U2F in Odoo
-------------------------------------------------------------------

.. raw:: html

   <iframe width="560" height="315" src="https://www.youtube.com/embed/-KhPDMkcOlU" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen>

.. raw:: html

   </iframe>
