Verify Sealed Hardware
======================

.. contents:: :local:

If you ordered your NitroPad with sealed screws and in a sealed bag, it allows you to check if the NitroPad has been tampered with during shipping.

The bag and all screws on the bottom of the device have been sealed. For the bag and each of these screws you have received a photo by e-mail. The orientation of the photos is such that the battery is on top.

1. Check each screw individually to see if its individual appearance
   matches the photo. It is best to use a magnifying glass or macro lens
   for this purpose. The screws are numbered as follows.
   
   Nitropad NV41:
   
   .. figure:: /nitropad/images/nv41_sealed.jpg
      :alt: NV41

   Nitropad NS50:

   .. figure:: /nitropad/images/ns50_sealed.jpg
      :alt: NS50

   NitroPad X230:

   .. figure:: /nitropad/images/SchraubenmarkierungX230.jpg
      :alt: X230

   NitroPad T430:

   .. figure:: /nitropad/images/SchraubenmarkierungT430.jpg
      :alt: T430


   This example shows a sealed screw whose glitter represents an
   individual pattern.

   .. figure:: /nitropad/images/Schraube.jpg
      :alt: img


2. If the bag or the screws do not match the photos sent, an
   unauthorized opening of your NitroPad cannot be excluded. In this
   case please contact us to arrange further action.
