name: CI - Nightly
on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  check-hyperlinks:
    name: Check hyperlinks
    runs-on: ubuntu-latest
    container: python:3.11
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create virtual environment
        run: make venv
      - name: Check hyperlinks
        run: make check-hyperlinks-nightly
